import { ensureWorkerShareRenderer } from './src/lib/share-render-png.worker'
import yogaWasm from './node_modules/satori/yoga.wasm?module'
import {
  WORKER_SVG_RESPONSE_HEADER,
  WORKER_SVG_TRANSPARENT_HEADER,
} from './src/lib/share-render-runtime'

// Generated by `opennextjs-cloudflare build` before Wrangler bundles this entry.
// @ts-expect-error generated build artifact is absent during the Next.js typecheck
import openNextHandler from './.open-next/worker.js'

const IMAGE_RENDER_PATHS = new Set([
  '/api/share/render',
  '/api/poster',
  '/api/poster-preview',
])

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void
  passThroughOnException(): void
}

type AssetFetcher = {
  fetch(request: Request): Promise<Response>
}

type WorkerEnv = Record<string, unknown> & {
  ASSETS: AssetFetcher
  PEAK_TREKKER_YOGA_WASM?: WebAssembly.Module
}

const MAX_INTERNAL_SVG_BYTES = 5 * 1024 * 1024
const SHARE_RENDER_REQUEST_ID_HEADER = 'x-peak-trekker-render-id'

function loadWorkerFontBuffers(env: WorkerEnv, requestUrl: string) {
  return Promise.all([
    '/fonts/NotoSansSC-Regular.otf',
    '/fonts/NotoSansSC-Bold.otf',
  ].map(async (path) => {
    const response = await env.ASSETS.fetch(new Request(new URL(path, requestUrl)))
    if (!response.ok) throw new Error(`Worker font asset unavailable: ${path}`)
    return response.arrayBuffer()
  }))
}

function workerRenderFailure(errorId: string, code: 'SR-FONT' | 'SR-SVG-SIZE' | 'SR-PNG' | 'SR-UNKNOWN') {
  return Response.json(
    {
      error: 'Unable to render share image',
      code,
      errorId,
    },
    {
      status: 500,
      headers: {
        'Cache-Control': 'no-store',
        [SHARE_RENDER_REQUEST_ID_HEADER]: errorId,
      },
    },
  )
}

async function renderWorkerSvgResponse(request: Request, env: WorkerEnv, response: Response) {
  if (response.headers.get(WORKER_SVG_RESPONSE_HEADER) !== '1') return response

  const isShareRender = new URL(request.url).pathname === '/api/share/render'
  const errorId = response.headers.get(SHARE_RENDER_REQUEST_ID_HEADER) ?? crypto.randomUUID()

  const contentLength = Number(response.headers.get('Content-Length'))
  if (!Number.isFinite(contentLength) || contentLength <= 0 || contentLength > MAX_INTERNAL_SVG_BYTES) {
    if (isShareRender) return workerRenderFailure(errorId, 'SR-SVG-SIZE')
    throw new Error('Invalid internal SVG response size')
  }

  let svg: string
  try {
    svg = await response.text()
  } catch (error) {
    if (isShareRender) return workerRenderFailure(errorId, 'SR-UNKNOWN')
    throw error
  }

  let renderer: Awaited<ReturnType<typeof ensureWorkerShareRenderer>>
  try {
    renderer = await ensureWorkerShareRenderer()
  } catch (error) {
    if (isShareRender) return workerRenderFailure(errorId, 'SR-PNG')
    throw error
  }

  // Satori share SVGs contain glyph paths, so Resvg needs no duplicate Noto buffers.
  // Legacy poster SVGs may still contain text and keep their invocation-local fonts.
  const fontBuffers = isShareRender ? undefined : await loadWorkerFontBuffers(env, request.url)

  try {
    const png = await renderer({
      svg,
      ...(fontBuffers ? { fontBuffers } : {}),
      transparent: response.headers.get(WORKER_SVG_TRANSPARENT_HEADER) === '1',
    })
    const headers = new Headers(response.headers)
    headers.set('Content-Type', 'image/png')
    headers.set('Content-Length', String(png.byteLength))
    headers.delete(WORKER_SVG_RESPONSE_HEADER)
    headers.delete(WORKER_SVG_TRANSPARENT_HEADER)
    return new Response(png, { status: response.status, headers })
  } catch (error) {
    if (isShareRender) return workerRenderFailure(errorId, 'SR-PNG')
    throw error
  }
}

export default {
  async fetch(request: Request, env: WorkerEnv, context: WorkerContext) {
    if (!IMAGE_RENDER_PATHS.has(new URL(request.url).pathname)) {
      return openNextHandler.fetch(request, env, context)
    }

    const response = await openNextHandler.fetch(request, {
      ...env,
      PEAK_TREKKER_YOGA_WASM: yogaWasm,
    }, context)
    return renderWorkerSvgResponse(request, env, response)
  },
}
