import { ensureWorkerShareRenderer } from './src/lib/share-render-png.worker'
import yogaWasm from './node_modules/satori/yoga.wasm?module'
import {
  WORKER_SVG_RESPONSE_HEADER,
  WORKER_SVG_TRANSPARENT_HEADER,
} from './src/lib/share-render-runtime'

// Generated by `opennextjs-cloudflare build` before Wrangler bundles this entry.
// @ts-expect-error generated build artifact is absent during the Next.js typecheck
import openNextHandler from './.open-next/worker.js'

const IMAGE_RENDER_PATHS = new Set([
  '/api/share/render',
  '/api/poster',
  '/api/poster-preview',
])

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void
  passThroughOnException(): void
}

type AssetFetcher = {
  fetch(request: Request): Promise<Response>
}

type WorkerEnv = Record<string, unknown> & {
  ASSETS: AssetFetcher
  PEAK_TREKKER_YOGA_WASM?: WebAssembly.Module
}

const MAX_INTERNAL_SVG_BYTES = 5 * 1024 * 1024
let workerFontBuffersReady: Promise<ArrayBuffer[]> | null = null

function loadWorkerFontBuffers(env: WorkerEnv, requestUrl: string) {
  workerFontBuffersReady ??= Promise.all([
    '/fonts/NotoSansSC-Regular.otf',
    '/fonts/NotoSansSC-Bold.otf',
  ].map(async (path) => {
    const response = await env.ASSETS.fetch(new Request(new URL(path, requestUrl)))
    if (!response.ok) throw new Error(`Worker font asset unavailable: ${path}`)
    return response.arrayBuffer()
  }))
  return workerFontBuffersReady
}

async function renderWorkerSvgResponse(request: Request, env: WorkerEnv, response: Response) {
  if (response.headers.get(WORKER_SVG_RESPONSE_HEADER) !== '1') return response

  const contentLength = Number(response.headers.get('Content-Length'))
  if (!Number.isFinite(contentLength) || contentLength <= 0 || contentLength > MAX_INTERNAL_SVG_BYTES) {
    throw new Error('Invalid internal SVG response size')
  }
  const svg = await response.text()
  const [renderer, fontBuffers] = await Promise.all([
    ensureWorkerShareRenderer(),
    loadWorkerFontBuffers(env, request.url),
  ])
  const png = await renderer({
    svg,
    fontBuffers,
    transparent: response.headers.get(WORKER_SVG_TRANSPARENT_HEADER) === '1',
  })
  const headers = new Headers(response.headers)
  headers.set('Content-Type', 'image/png')
  headers.set('Content-Length', String(png.byteLength))
  headers.delete(WORKER_SVG_RESPONSE_HEADER)
  headers.delete(WORKER_SVG_TRANSPARENT_HEADER)
  return new Response(png, { status: response.status, headers })
}

export default {
  async fetch(request: Request, env: WorkerEnv, context: WorkerContext) {
    if (!IMAGE_RENDER_PATHS.has(new URL(request.url).pathname)) {
      return openNextHandler.fetch(request, env, context)
    }

    const response = await openNextHandler.fetch(request, {
      ...env,
      PEAK_TREKKER_YOGA_WASM: yogaWasm,
    }, context)
    return renderWorkerSvgResponse(request, env, response)
  },
}
